### ISSUE TITLE
Crashes on Every Exit

### ISSUE THREAD

**Issue by hl2guide** [KurtBestor/Hitomi-Downloader#3569] opened 2021-07-17 00:31 UTC
For me the app crashes every time I quit.

It causes a crashdump at: `C:\Users\Dean\AppData\Local\CrashDumps`

with filenames like: `hitomi_downloader_GUI.exe.17892.dmp`

May be the app has a memory leak on exit?

Has anyone else noticed this?

**Comment by KurtBestor** [comment] 2021-07-19 16:55
I can't reproduce on my end.

**Comment by KurtBestor** [comment] 2021-07-19 16:56
I can't reproduce on my end. What's your OS?

**Comment by hl2guide** [comment] 2021-07-21 12:39
Windows 10 (21H1).

I could send you the dump file if you need it for diagnosis.

**Comment by poyshu** [comment] 2021-11-08 08:08
I think this has been fixed in v3.7c? I'm not having any error ever since.

I'm guessing this is the same issue as #3975. Seems the error message will only show when Windows Error Reporting service is disabled.

Thanks for the wonderful work again.

**Closed** 2021-11-18 05:59 UTC
