### ISSUE TITLE
픽시브 언제 고쳐지나요...

### ISSUE THREAD

**Issue by NyaHan16** [KurtBestor/Hitomi-Downloader#6762] opened 2024-01-03 07:11 UTC
사용법에 적혀있는 https://chromewebstore.google.com/detail/cclelndahbckbenkjhflpdbgdldlbecc
이걸로도 쿠키를 불러와봤고

https://github.com/KurtBestor/Hitomi-Downloader/wiki/Chrome-Extension
이걸로도 쿠키 를 불러와도 여전히 픽시브는 오류가 납니다..

4분 57초 뒤 다시 시작: Invalid: [pixiv] https://www.pixiv.net/artworks/114786184

version: 4.0+ (23-12-31 03:49:53 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 49f806756e3f409dbdadfe4d1d32a8c1
input: https://www.pixiv.net/artworks/114786184
type: pixiv
single: False
url: https://www.pixiv.net/artworks/114786184
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1704265741.4816022 (24-01-03 07:09:01 UTC) - 104s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html

stop
Traceback (most recent call last):
 File "utils", line 1362, in start
 File "extractor\pixiv_downloader", line 46, in init
 File "clf2", line 176, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://www.pixiv.net/artworks/114786184  (100.1s)

오류 문?구 입니다..

**Comment by KurtBestor** [comment] 2024-01-03 08:59
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/6727

**Closed** 2024-01-03 08:59 UTC
