### ISSUE TITLE
vimeo 동영상 다운로드가 진행되지않습니다.

### ISSUE THREAD

**Issue by jgjang** [KurtBestor/Hitomi-Downloader#6089] opened 2023-06-25 21:47 UTC
Invalid: [vimeo] https://vimeo.com/832060891

version: 3.8d (23-06-23 04:15:53 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 444f92e2f41c43f2a2eda167d97cb08d
input: https://vimeo.com/832060891
type: vimeo
single: True
url: https://vimeo.com/832060891
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1687729148.02863 (23-06-25 21:39:08 UTC) - 22s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
[debug] [vimeo] Extracting URL: https://vimeo.com/832060891
[debug] [vimeo] 832060891: Downloading webpage
[debug] [vimeo] 832060891: Downloading JSON metadata
[debug] [vimeo] 832060891: Downloading JSON metadata
[warning] [vimeo] 832060891: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
[debug] [vimeo] 832060891: Downloading jwt token
[debug] [vimeo] 832060891: Downloading JSON metadata
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic m3u8 information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic m3u8 information
[debug] [vimeo] 832060891: Downloading fastly_skyfire m3u8 information
[debug] [vimeo] 832060891: Downloading fastly_skyfire m3u8 information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic MPD information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic MPD information
[debug] [vimeo] 832060891: Downloading fastly_skyfire MPD information
[debug] [vimeo] 832060891: Downloading fastly_skyfire MPD information
[debug] [info] 832060891: Downloading subtitles: en-x-autogen
[debug] [vimeo] Extracting URL: https://vimeo.com/832060891
[debug] [vimeo] 832060891: Downloading webpage
[debug] [vimeo] 832060891: Downloading JSON metadata
[debug] [vimeo] 832060891: Downloading JSON metadata
[warning] [vimeo] 832060891: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
[debug] [vimeo] 832060891: Downloading jwt token
[debug] [vimeo] 832060891: Downloading JSON metadata
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic m3u8 information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic m3u8 information
[debug] [vimeo] 832060891: Downloading fastly_skyfire m3u8 information
[debug] [vimeo] 832060891: Downloading fastly_skyfire m3u8 information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic MPD information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic MPD information
[debug] [vimeo] 832060891: Downloading fastly_skyfire MPD information
[debug] [vimeo] 832060891: Downloading fastly_skyfire MPD information
[debug] [info] 832060891: Downloading subtitles: en-x-autogen
[debug] [vimeo] Extracting URL: https://vimeo.com/832060891
[debug] [vimeo] 832060891: Downloading webpage
[debug] [vimeo] 832060891: Downloading JSON metadata
[debug] [vimeo] 832060891: Downloading JSON metadata
[warning] [vimeo] 832060891: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
[debug] [vimeo] 832060891: Downloading jwt token
[debug] [vimeo] 832060891: Downloading JSON metadata
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic m3u8 information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic m3u8 information
[debug] [vimeo] 832060891: Downloading fastly_skyfire m3u8 information
[debug] [vimeo] 832060891: Downloading fastly_skyfire m3u8 information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic MPD information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic MPD information
[debug] [vimeo] 832060891: Downloading fastly_skyfire MPD information
[debug] [vimeo] 832060891: Downloading fastly_skyfire MPD information
[debug] [info] 832060891: Downloading subtitles: en-x-autogen
[debug] [vimeo] Extracting URL: https://vimeo.com/832060891
[debug] [vimeo] 832060891: Downloading webpage
[debug] [vimeo] 832060891: Downloading JSON metadata
[debug] [vimeo] 832060891: Downloading JSON metadata
[warning] [vimeo] 832060891: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
[debug] [vimeo] 832060891: Downloading jwt token
[debug] [vimeo] 832060891: Downloading JSON metadata
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic m3u8 information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic m3u8 information
[debug] [vimeo] 832060891: Downloading fastly_skyfire m3u8 information
[debug] [vimeo] 832060891: Downloading fastly_skyfire m3u8 information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic MPD information
[debug] [vimeo] 832060891: Downloading akfire_interconnect_quic MPD information
[debug] [vimeo] 832060891: Downloading fastly_skyfire MPD information
[debug] [vimeo] 832060891: Downloading fastly_skyfire MPD information
[debug] [info] 832060891: Downloading subtitles: en-x-autogen
'RequestsCookieJar' object has no attribute 'get_cookie_header'
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\vimeo_downloader", line 21, in read
 File "utils", line 850, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in wrapper
 File "constants", line 897, in wrapper
 File "extractor\vimeo_downloader", line 44, in get
 File "ytdl", line 440, in extract_info
 File "C:\Users\JANGJA~1\AppData\Local\Temp\_MEI63162\ytdl_274ccb5c\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\JANGJA~1\AppData\Local\Temp\_MEI63162\ytdl_274ccb5c\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\JANGJA~1\AppData\Local\Temp\_MEI63162\ytdl_274ccb5c\yt_dlp\yt_dlp\YoutubeDL", line 1652, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\JANGJA~1\AppData\Local\Temp\_MEI63162\ytdl_274ccb5c\yt_dlp\yt_dlp\YoutubeDL", line 1711, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\JANGJA~1\AppData\Local\Temp\_MEI63162\ytdl_274ccb5c\yt_dlp\yt_dlp\YoutubeDL", line 2673, in process_video_result
   format['http_headers'] = self._calc_headers(collections.ChainMap(format, info_dict))
 File "C:\Users\JANGJA~1\AppData\Local\Temp\_MEI63162\ytdl_274ccb5c\yt_dlp\yt_dlp\YoutubeDL", line 2410, in _calc_headers
   cookies = self.cookiejar.get_cookie_header(info_dict['url'])
AttributeError: 'RequestsCookieJar' object has no attribute 'get_cookie_header'

Invalid: fail=True
EOT: https://vimeo.com/832060891  (19.7s)

**Comment by KurtBestor** [comment] 2023-06-26 00:48
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/6086

**Comment by jgjang** [comment] 2023-06-26 21:27
프리뷰버전으로 정상작동합니다.

**Closed** 2023-06-26 21:28 UTC
Labels: duplicate
