### ISSUE TITLE
이거 추가가능한가요?

### ISSUE THREAD

**Issue by BadDrago895** [KurtBestor/Hitomi-Downloader#3227] opened 2021-03-20 11:22 UTC
https://tbib.org/ 
이거추가해주시면 좋을거같습니다

**Comment by KurtBestor** [comment] 2021-04-07 14:38
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/3226

**Closed by KurtBestor** 2021-04-07 14:38 UTC
