### ISSUE TITLE
sankaku 2,000p 이상 다운로드되지 않는 현상이 있어요.

### ISSUE THREAD

**Issue by donato-alpa** [KurtBestor/Hitomi-Downloader#3413] opened 2021-05-21 00:16 UTC
글자수 제한 걸려서 이미지 로고 재외하고 올립니다.

---------------------------------------------------------------------------------------------------------------

[chan] kase_daiki

version: 3.3b (21-05-16 18:39:30 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 955cfc09e2bc473ca131991ad024e458
input: https://chan.sankakucomplex.com/?tags=kase_daiki
type: sankaku
single: False
url: https://chan.sankakucomplex.com/?tags=kase_daiki
dir: hitomi_downloaded_sankaku\[chan] kase_daiki
zip: 
artist: None
valid / done: True / True
range / range_p: ~2000 / None
time: 1621495595.5260575 (May 20)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.05.16
pinned: False
extras: {}
changed: True

[Gallery]
None

Traceback (most recent call last):
File "downloader", line 287, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\sankaku_downloader", line 278, in get_imgs
File "downloader", line 338, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error

stop
EOT: https://chan.sankakucomplex.com/?tags=kase_daiki (604.9s)

-----------------------------------------------------------------------------------

[chan] nishieda

version: 3.3b (21-05-16 18:39:30 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 8e07225f31a440b2ba7c53b3723b8605
input: https://chan.sankakucomplex.com/?tags=nishieda
type: sankaku
single: False
url: https://chan.sankakucomplex.com/?tags=nishieda
dir: hitomi_downloaded_sankaku\[chan] nishieda
zip: 
artist: None
valid / done: True / True
range / range_p: ~2000 / None
time: 1621496348.3891702 (May 20)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.05.16
pinned: False
extras: {}
changed: True

[Gallery]
None

Traceback (most recent call last):
File "downloader", line 287, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\sankaku_downloader", line 278, in get_imgs
File "downloader", line 338, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error

stop
EOT: https://chan.sankakucomplex.com/?tags=nishieda (609.9s)

-------------------------------------------------------------------------------------------------------

[chan] kaisen_chuui

version: 3.3b (21-05-16 18:39:30 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / c5782f74f1714bcd9912123a981a8d85
input: https://chan.sankakucomplex.com/?tags=kaisen_chuui
type: sankaku
single: False
url: https://chan.sankakucomplex.com/?tags=kaisen_chuui
dir: hitomi_downloaded_sankaku\[chan] kaisen_chuui
zip: 
artist: None
valid / done: True / True
range / range_p: ~2000 / None
time: 1621497030.3347516 (May 20)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.05.16
pinned: False
extras: {}
changed: True

[Gallery]
None

Traceback (most recent call last):
File "downloader", line 287, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\sankaku_downloader", line 278, in get_imgs
File "downloader", line 338, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error

stop
EOT: https://chan.sankakucomplex.com/?tags=kaisen_chuui (609.4s)

-----------------------------------------------------------------------------------------------------

원래는순서대로 2,169 - 3,019 - 2,437p의 분량입니다.

**Comment by KurtBestor** [comment] 2021-05-21 03:48
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/3366

**Closed by KurtBestor** 2021-05-21 03:48 UTC
