### ISSUE TITLE
chan.sankakucomplex.com/ still not working

### ISSUE THREAD

**Issue by unduesnow** [KurtBestor/Hitomi-Downloader#3995] opened 2021-11-06 08:21 UTC
restart, refresh readd nothing works, sometimes itll work after ages but only download a very small amount of pics

**Comment by KurtBestor** [comment] 2021-11-06 15:30
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/3843

**Closed by KurtBestor** 2021-11-06 15:30 UTC
