### ISSUE TITLE
웨이보가 다시 시작이 안 됩니다 

### ISSUE THREAD

**Issue by mju00rian** [KurtBestor/Hitomi-Downloader#2633] opened 2020-10-24 00:46 UTC
이번에 나온 테스트 버전도 사용해보고 했지만 변함없이 다시 시작 기능시 주황색 삼각형에 느낌표 표시가 뜨면서 '다시시작 실패; 복구됨' 이라는 메시지만 뜨고 다운로드가 이뤄지지 않고 있습니다
웨이보 쿠키는 넣었으며 관리자 권한으로 실행했습니다 

테스트 웨이보 링크  : weibo.com/u/5764605043

过期米线线喵 (weibo_5764605043)

version: 2.8 (20-10-23 21:23:43 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 763
group: False
input: weibo.com/u/5764605043
dir: hitomi_downloaded_weibo\过期米线线喵 (weibo_5764605043)
zip: 
type: weibo
artist: None
url: weibo.com/u/5764605043
valid: False
done: True
range: None
range_p: None
single: False
time: 1601884710.959018 (Oct 5)
tags: []
goodbyedpi: True
lock: True
color: invalid_done
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_weibo\过期米线线喵 (weibo_5764605043)\[20-10-03] 4555997439197436.jpg
[0002] hitomi_downloaded_weibo\过期米线线喵 (weibo_5764605043)\[20-10-03] 4555997439197400.jpg
[0003] hitomi_downloaded_weibo\过期米线线喵 (weibo_5764605043)\[20-10-03] 4555997439197396.jpg
주르륵 파일 목록들이 이어집니다 
[0409] hitomi_downloaded_weibo\过期米线线喵 (weibo_5764605043)\[17-07-03] 4125524686433641.jpg
[0410] hitomi_downloaded_weibo\过期米线线喵 (weibo_5764605043)\[17-07-03] 4125477433410679.jpg
[0411] hitomi_downloaded_weibo\过期米线线喵 (weibo_5764605043)\[15-11-19] 3910672273514377.jpg

[URLs]

[Messages]
clf solved
uid: 5764605043, oid:1005055764605043
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\weibo_downloader", line 49, in read
File "extractor\weibo_downloader", line 155, in get_imgs
File "extractor\weibo_downloader", line 142, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/5764605043

invalid; revert

**Comment by KurtBestor** [comment] 2020-11-10 17:38
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/2554

**Closed by KurtBestor** 2020-11-10 17:38 UTC
