### ISSUE TITLE
웨이보가 다운로드가 되지 않습니다 

### ISSUE THREAD

**Issue by mju00rian** [KurtBestor/Hitomi-Downloader#2717] opened 2020-11-10 01:57 UTC
언제나 감사히 잘 사용하고 있습니다.

그런데 제 환경에서 웨이보가 제대로 동작하지 않아 문의해봅니다.

테스트 URL : weibo.com/u/1752376494
브라우저로는 정상 접속됩니다

기존 다운로드 재시작시 오류 메시지는 '주황색 경고 아이콘과 함께 다시 시작 실패; 복구됨'  이라고 뜹니다

정보창에는 
Money不太甜 (weibo_1752376494)

version: 2.8 (20-10-31 05:00:31 UTC)
platform: Windows-10-10.0.18362-SP0
order: 621
group: False
input: weibo.com/u/1752376494
dir: hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)
zip: 
type: weibo
artist: None
url: weibo.com/u/1752376494
valid: False
done: True
range: None
range_p: None
single: False
time: 1601884710.2763963 (Oct 5)
tags: []
goodbyedpi: False
lock: True
color: invalid_done
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-09-10] 4547686612606599.jpg
[0002] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-09-01] 4544430190231557.jpg
[0003] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-09-01] 4544430186299887.jpg
~파일 목록들~
[0029] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[19-02-19] 4341426933658955.jpg
[0030] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[14-07-26] 3736619533338636.jpg

[URLs]

[Messages]
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\weibo_downloader", line 49, in read
File "extractor\weibo_downloader", line 155, in get_imgs
File "extractor\weibo_downloader", line 142, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\weibo_downloader", line 49, in read
File "extractor\weibo_downloader", line 155, in get_imgs
File "extractor\weibo_downloader", line 142, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\weibo_downloader", line 49, in read
File "extractor\weibo_downloader", line 155, in get_imgs
File "extractor\weibo_downloader", line 142, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\weibo_downloader", line 50, in read
File "extractor\weibo_downloader", line 156, in get_imgs
File "extractor\weibo_downloader", line 143, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\weibo_downloader", line 50, in read
File "extractor\weibo_downloader", line 156, in get_imgs
File "extractor\weibo_downloader", line 143, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\weibo_downloader", line 50, in read
File "extractor\weibo_downloader", line 156, in get_imgs
File "extractor\weibo_downloader", line 143, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\weibo_downloader", line 50, in read
File "extractor\weibo_downloader", line 156, in get_imgs
File "extractor\weibo_downloader", line 143, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\weibo_downloader", line 50, in read
File "extractor\weibo_downloader", line 156, in get_imgs
File "extractor\weibo_downloader", line 143, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert

이렇게 뜨며 

다시 시작이 아니라 목록에서 삭제후 새로 추가시에는 
빨간색 글씨로 'invalid: [weibo] https://weibo.com/u/1752376494' 이렇게 뜨며 
정보 창의 내역은 
Invalid: [weibo] https://weibo.com/u/1752376494

version: 3.2a (20-10-31 05:00:31 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://weibo.com/u/1752376494
dir: 
zip: 
type: weibo
artist: None
url: https://weibo.com/u/1752376494
valid: False
done: True
range: None
range_p: None
single: False
time: 1604973204.722615 (Nov 10)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\weibo_downloader", line 50, in read
File "extractor\weibo_downloader", line 156, in get_imgs
File "extractor\weibo_downloader", line 143, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: https://weibo.com/u/1752376494

이와 같습니다 

웨이보 쿠키는 크롬에서 웨이보 로그인 후 크롬의 확장 프로그램 Export Cookies.txt 을 사용했습니다

**Comment by KurtBestor** [comment] 2020-11-10 17:38
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/2554

**Closed by KurtBestor** 2020-11-10 17:38 UTC
